version: 2.1

executors:
  windows-gpu-prototype:
    machine:
      resource_class: windows.gpu.small.prototype
      image: windows-server-2019-nvidia:201908-28
      shell: powershell.exe -ExecutionPolicy Bypass

jobs:
  smoketest_windows:
    executor: windows-gpu-prototype
    steps:
      - checkout
      - run:
          command: |
            choco install miniconda3
            $env:Path += ";C:\tools\miniconda3\Scripts;C:\tools\miniconda3;C:\Program Files\NVIDIA Corporation\NVSMI"
            conda install -yq -c pytorch pytorch
            nvidia-smi
            python -c "import torch; print(torch.cuda.device_count())"

workflows:
  build:
    jobs:
      - smoketest_windows
