version: 2.1

executors:
  windows-gpu-prototype:
    machine:
      resource_class: windows.gpu.small.prototype
      image: windows-server-2019-nvidia:201908-28
      shell: powershell.exe -ExecutionPolicy Bypass

jobs:
  circleci_consistency:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            pip install --user --progress-bar off jinja2
            python .circleci/regenerate.py
            git diff --exit-code || (echo ".circleci/config.yml not in sync with config.yml.in! Run .circleci/regenerate.py to update config"; exit 1)

  smoketest_windows:
    executor: windows-gpu-prototype
    steps:
      - checkout
      - run:
          command: |
            choco install miniconda3
            $env:Path += ";C:\tools\miniconda3\Scripts"
            conda install -c pytorch pytorch
            nvidia-smi
            python -c "import torch; print(torch.cuda.device_count())"

workflows:
  build:
    jobs:
      - circleci_consistency
      - smoketest_windows